import { useState, useRef, useEffect } from 'react';
import html2pdf from 'html2pdf.js';

interface Recommendation {
  id: number;
  issue: string;
  category: string;
  location: string;
  severity: string;
  suggestion?: string | null;
}

interface ExportDropdownProps {
  score?: number;
  breakdown?: Record<string, number>;
  recommendations?: Recommendation[];
  reportContentId?: string;
}

export default function ExportDropdown({ 
  score = 0, 
  breakdown = {}, 
  recommendations = [],
  reportContentId = 'report-content'
}: ExportDropdownProps) {
  const [isOpen, setIsOpen] = useState(false);
  const dropdownRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    function handleClickOutside(event: MouseEvent) {
      if (dropdownRef.current && !dropdownRef.current.contains(event.target as Node)) {
        setIsOpen(false);
      }
    }
    document.addEventListener('mousedown', handleClickOutside);
    return () => document.removeEventListener('mousedown', handleClickOutside);
  }, []);

  const handleDownloadPDF = async () => {
    const element = document.getElementById(reportContentId);
    if (!element) {
      alert('Report content not found');
      return;
    }

    const opt = {
      margin: 10,
      filename: `CV_Analysis_Report_${new Date().toISOString().split('T')[0]}.pdf`,
      image: { type: 'jpeg' as const, quality: 0.98 },
      html2canvas: { scale: 2 },
      jsPDF: { unit: 'mm' as const, format: 'a4' as const, orientation: 'portrait' as const }
    };

    try {
      await html2pdf().set(opt).from(element).save();
    } catch (err) {
      console.error('Failed to generate PDF:', err);
      alert('Failed to generate PDF');
    }
  };

  const handleCopyToClipboard = async () => {
    let textContent = `CV ANALYSIS REPORT\n`;
    textContent += `Generated: ${new Date().toLocaleDateString()}\n\n`;
    textContent += `SCORE: ${score}%\n\n`;
    textContent += `SCORE BREAKDOWN:\n`;

    Object.entries(breakdown).forEach(([category, value]) => {
      const formattedCategory = category.replace(/_/g, ' ').replace(/\b\w/g, l => l.toUpperCase());
      textContent += `- ${formattedCategory}: ${value}\n`;
    });

    textContent += `\nRECOMMENDATIONS (${recommendations.length} total):\n\n`;

    recommendations.forEach((rec, index) => {
      textContent += `${index + 1}. ${rec.issue}\n`;
      textContent += `   Category: ${rec.category}\n`;
      textContent += `   Location: ${rec.location}\n`;
      textContent += `   Severity: ${rec.severity}\n`;
      if (rec.suggestion) {
        textContent += `   Suggestion: ${rec.suggestion}\n`;
      }
      textContent += `\n`;
    });

    textContent += `\n---\nGenerated by GetHiredAlly CV Optimizer\nhttps://gethiredally.com`;

    try {
      await navigator.clipboard.writeText(textContent);
      alert('Report copied to clipboard!');
    } catch (err) {
      console.error('Failed to copy:', err);
      alert('Failed to copy to clipboard');
    }
  };

  const handleSendToEmail = () => {
    const subject = encodeURIComponent(
      `CV Analysis Report - ${new Date().toLocaleDateString()}`
    );

    let body = `CV ANALYSIS REPORT\n\n`;
    body += `Score: ${score}%\n\n`;
    body += `Key Findings:\n`;
    body += `- Total Recommendations: ${recommendations.length}\n`;
    
    const criticalCount = recommendations.filter(r => r.severity === 'critical').length;
    const highCount = recommendations.filter(r => r.severity === 'high').length;
    
    body += `- Critical Issues: ${criticalCount}\n`;
    body += `- High Priority: ${highCount}\n\n`;
    body += `Top 5 Recommendations:\n`;

    recommendations.slice(0, 5).forEach((rec, index) => {
      body += `${index + 1}. ${rec.issue}\n`;
    });

    body += `\n---\nGenerated by GetHiredAlly CV Optimizer\nhttps://gethiredally.com`;

    const encodedBody = encodeURIComponent(body);
    window.location.href = `mailto:?subject=${subject}&body=${encodedBody}`;
  };

  const handleExport = (type: string) => {
    setIsOpen(false);
    
    switch (type) {
      case 'pdf':
        handleDownloadPDF();
        break;
      case 'copy':
        handleCopyToClipboard();
        break;
      case 'email':
        handleSendToEmail();
        break;
      default:
        console.log('Unknown export type:', type);
    }
  };

  return (
    <div className="relative" ref={dropdownRef}>
      <button
        onClick={() => setIsOpen(!isOpen)}
        className="flex items-center gap-2 px-4 py-2 bg-white border border-gray-300 rounded-lg hover:bg-gray-50 transition-colors text-sm font-medium"
      >
        <span>📥</span>
        <span>Export Report</span>
        <span className={`transition-transform duration-200 ${isOpen ? 'rotate-180' : ''}`}>
          ▼
        </span>
      </button>
      
      {isOpen && (
        <div className="absolute right-0 mt-2 w-48 bg-white border border-gray-200 rounded-lg shadow-lg z-50">
          <button
            onClick={() => handleExport('pdf')}
            className="w-full px-4 py-3 text-left hover:bg-gray-50 flex items-center gap-3 rounded-t-lg text-sm"
          >
            <span>📄</span>
            <span>Download as PDF</span>
          </button>
          <button
            onClick={() => handleExport('copy')}
            className="w-full px-4 py-3 text-left hover:bg-gray-50 flex items-center gap-3 border-t border-gray-100 text-sm"
          >
            <span>📋</span>
            <span>Copy to Clipboard</span>
          </button>
          <button
            onClick={() => handleExport('email')}
            className="w-full px-4 py-3 text-left hover:bg-gray-50 flex items-center gap-3 border-t border-gray-100 rounded-b-lg text-sm"
          >
            <span>📧</span>
            <span>Send to Email</span>
          </button>
        </div>
      )}
    </div>
  );
}
