/**
 * Markdown Generator for DocStyler
 * Generates styled .md file with header and footer
 */

import { COMPANY, FOOTER, SERVICES, formatDateTime } from '../styles/documentStyles';

/**
 * Generate header section for markdown
 * @param {Object} options - Document options
 * @returns {string} Markdown header
 */
const generateHeader = (options) => {
  const { title, service, metadata } = options;
  const serviceName = SERVICES[service] || service || 'GetHiredAlly';
  
  let header = `# ${title}\n\n`;
  header += `**Service:** ${serviceName}  \n`;
  header += `**Generated:** ${formatDateTime()}  \n`;
  
  if (metadata?.score !== undefined) {
    header += `**Score:** ${metadata.score}/100 (${metadata.grade || 'N/A'})  \n`;
  }
  
  header += '\n---\n\n';
  
  return header;
};

/**
 * Generate footer section for markdown
 * @returns {string} Markdown footer
 */
const generateFooter = () => {
  const links = FOOTER.links
    .map(link => `[${link.text}](${link.url})`)
    .join(FOOTER.separator);
  
  let footer = '\n---\n\n';
  footer += `*Generated by ${COMPANY.name}*  \n`;
  footer += `${links}\n`;
  
  return footer;
};

/**
 * Generate complete Markdown document
 * @param {string} content - Main content (markdown)
 * @param {Object} options - Document options
 * @returns {string} Complete markdown document
 */
export const generateMD = (content, options = {}) => {
  const {
    title = 'Document',
    service = '',
    fileName = 'document',
    metadata = {},
    includeHeader = true,
    includeFooter = true,
  } = options;
  
  let document = '';
  
  // Add header
  if (includeHeader) {
    document += generateHeader({ title, service, metadata });
  }
  
  // Add main content
  document += content || '';
  
  // Add footer
  if (includeFooter) {
    document += generateFooter();
  }
  
  return document;
};

/**
 * Generate and download Markdown file
 * @param {string} content - Main content
 * @param {Object} options - Document options
 */
export const downloadMD = (content, options = {}) => {
  const { fileName = 'document' } = options;
  
  const markdown = generateMD(content, options);
  const blob = new Blob([markdown], { type: 'text/markdown;charset=utf-8' });
  
  // Create download link
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = `${fileName}.md`;
  
  // Trigger download
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  
  // Cleanup
  URL.revokeObjectURL(url);
};

export default { generateMD, downloadMD };
