import { useState, useEffect } from 'react'
import { useNavigate, useParams, Link } from 'react-router-dom'
import { 
  ArrowLeft, CheckCircle, FileText, File, 
  FileCode, Home, Columns, ArrowRight
} from 'lucide-react'
import { isAuthenticated, getAuthToken } from '@/lib/auth'
import ReactMarkdown from 'react-markdown'
import remarkGfm from 'remark-gfm'
import CVScoreCircle from './cv-optimizer/CVScoreCircle'
import DocStyler from './common/DocStyler/DocStyler'
import { SideBySide } from './common/SideBySide'

interface CategoryImprovement {
  issues_fixed: number
  total_issues: number
  improvement: number
  max_possible: number
  before: number
  after: number
}

interface FixedData {
  scan_id: string
  original_cv_content: string
  fixed_cv_content: string
  total_issues: number
  issues: Array<{
    id: number
    issue: string
    severity: string
    category: string
    location: string
    current_text: string
    suggested_fix: string
    is_auto_fixable?: boolean
  }>
  status: string
  original_score?: number
  fixed_score?: number
  improvement?: number
  category_improvements?: Record<string, CategoryImprovement>
  total_issues_fixed?: number
  changes?: Array<{ category: string; before: string; after: string; explanation: string }>
  changes_summary?: { total_changes: number; by_category: Record<string, number> }
  total_changes?: number
}

const VIEW_MODES = [
  { id: 'original', label: 'Original', icon: FileText },
  { id: 'fixed', label: 'Fixed', icon: CheckCircle },
  { id: 'sidebyside', label: 'Side by Side', icon: Columns }
]

export function CVFixedPage() {
  const navigate = useNavigate()
  const { scanId } = useParams()

  const [data, setData] = useState<FixedData | null>(null)
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState<string | null>(null)
  const [viewMode, setViewMode] = useState('sidebyside')
  const [isDownloading, setIsDownloading] = useState(false)

  const extractNameFromCV = (cvContent: string): string => {
    if (!cvContent) return ''
    const firstLine = cvContent.split('\n')[0] || ''
    const name = firstLine.replace(/CV|Resume|קורות חיים|#|\*\*/gi, '').trim()
    if (name && name.split(' ').length <= 4 && /^[a-zA-Z\s-]+$/.test(name)) {
      return name
    }
    return ''
  }

  const getFileName = (): string => {
    const userName = extractNameFromCV(data?.fixed_cv_content || '')
    return userName 
      ? `${userName} Optimized CV - GetHiredAlly.com`
      : 'Optimized CV - GetHiredAlly.com'
  }

  useEffect(() => {
    if (!isAuthenticated()) {
      navigate('/login')
      return
    }

    const fetchData = async () => {
      try {
        const token = getAuthToken()
        const response = await fetch(`/api/cv-optimizer/fixed/${scanId}?token=${token}`)

        if (!response.ok) {
          const errData = await response.json()
          throw new Error(errData.detail || 'Failed to load fixed CV')
        }

        const result = await response.json()
        setData(result)
      } catch (err) {
        setError(err instanceof Error ? err.message : 'Failed to load fixed CV')
      } finally {
        setLoading(false)
      }
    }

    fetchData()
  }, [scanId, navigate])

  const generateFallbackPDF = () => {
    const content = data?.fixed_cv_content || ''
    const printWindow = window.open('', '_blank')
    if (!printWindow) {
      alert('Please allow pop-ups to download the PDF.')
      return
    }
    printWindow.document.write(`
      <!DOCTYPE html>
      <html>
        <head>
          <title>${getFileName()}</title>
          <style>
            body { font-family: Arial, sans-serif; padding: 40px; line-height: 1.6; max-width: 800px; margin: 0 auto; }
            h1, h2, h3 { color: #1E5A85; }
            .header { border-bottom: 2px solid #1E5A85; padding-bottom: 10px; margin-bottom: 20px; }
            .footer { margin-top: 40px; padding-top: 10px; border-top: 1px solid #ddd; color: #666; font-size: 12px; }
            pre { white-space: pre-wrap; font-family: Arial, sans-serif; }
          </style>
        </head>
        <body>
          <div class="header">
            <h1>Your Optimized CV</h1>
            <p style="color: #666;">Score: ${data?.fixed_score || 'N/A'}/100 | Generated by GetHiredAlly.com</p>
          </div>
          <pre>${content.replace(/</g, '&lt;').replace(/>/g, '&gt;')}</pre>
          <div class="footer">
            <p>GetHiredAlly App | gethiredally.com</p>
          </div>
        </body>
      </html>
    `)
    printWindow.document.close()
    setTimeout(() => printWindow.print(), 500)
  }

  const handleDownloadPDF = async () => {
    setIsDownloading(true)
    try {
      await DocStyler.pdf(data?.fixed_cv_content || '', {
        title: 'Your Optimized CV',
        service: 'cv-optimizer',
        fileName: getFileName(),
        metadata: {
          score: data?.fixed_score,
          improvement: data?.improvement
        }
      })
    } catch (error) {
      console.error('PDF generation error:', error)
      try {
        generateFallbackPDF()
      } catch (fallbackError) {
        alert('Error generating PDF. Please try copying the text instead.')
      }
    } finally {
      setIsDownloading(false)
    }
  }

  const handleDownloadWord = async () => {
    setIsDownloading(true)
    try {
      await DocStyler.word(data?.fixed_cv_content || '', {
        title: 'Your Optimized CV',
        service: 'cv-optimizer',
        fileName: getFileName(),
        metadata: {
          score: data?.fixed_score,
          improvement: data?.improvement
        }
      })
    } catch (error) {
      console.error('Word generation error:', error)
      alert('Error generating Word document. Please try again.')
    } finally {
      setIsDownloading(false)
    }
  }

  const handleDownloadMD = async () => {
    setIsDownloading(true)
    try {
      await DocStyler.md(data?.fixed_cv_content || '', {
        title: 'Your Optimized CV',
        service: 'cv-optimizer',
        fileName: getFileName(),
        metadata: {
          score: data?.fixed_score,
          improvement: data?.improvement
        }
      })
    } catch (error) {
      console.error('MD generation error:', error)
      alert('Error generating Markdown. Please try again.')
    } finally {
      setIsDownloading(false)
    }
  }

  if (loading) {
    return (
      <div className="min-h-[calc(100vh-64px)] p-8 flex items-center justify-center" style={{ backgroundColor: '#FAF9F7' }}>
        <div className="text-center">
          <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-blue-600 mx-auto"></div>
          <p className="mt-4 text-gray-600">Loading fixed CV...</p>
        </div>
      </div>
    )
  }

  if (error || !data) {
    return (
      <div className="min-h-[calc(100vh-64px)] p-8 flex items-center justify-center" style={{ backgroundColor: '#FAF9F7' }}>
        <div className="max-w-md">
          <div className="bg-red-50 border border-red-200 rounded-lg p-6 text-center">
            <p className="text-red-700 mb-4">{error || 'Fixed CV not found'}</p>
            <Link to={`/service/cv-optimizer/report/${scanId}`} className="text-blue-600 hover:underline">
              Back to Report
            </Link>
          </div>
        </div>
      </div>
    )
  }

  return (
    <div className="min-h-[calc(100vh-64px)] p-8" style={{ backgroundColor: '#FAF9F7' }}>
      <div className="max-w-6xl mx-auto">
        <Link
          to={`/service/cv-optimizer/report/${scanId}`}
          className="flex items-center text-gray-600 hover:text-gray-800 mb-6"
        >
          <ArrowLeft size={20} className="mr-2" />
          Back to Report
        </Link>

        <div className="flex items-center justify-between mb-6">
          <div>
            <div className="flex items-center gap-3 mb-2">
              <div className="w-10 h-10 bg-green-100 rounded-full flex items-center justify-center">
                <CheckCircle size={24} className="text-green-600" />
              </div>
              <h1 className="text-2xl font-bold" style={{ color: '#1E3A5F' }}>
                Your Fixed CV
              </h1>
            </div>
            <p className="text-gray-600">
              {data.total_issues} issues have been corrected
            </p>
          </div>
        </div>

        {data.original_score !== undefined && data.fixed_score !== undefined && (
          <div className="bg-white border border-gray-200 rounded-xl p-8 mb-8">
            <div className="flex items-center justify-center gap-8">
              <CVScoreCircle 
                score={data.original_score} 
                size="medium" 
                label="Before"
                showMessage={false}
              />
              <div className="flex flex-col items-center">
                <ArrowRight size={32} className="text-gray-400" />
              </div>
              <CVScoreCircle 
                score={data.fixed_score} 
                size="medium" 
                label="After"
                showMessage={false}
              />
              <div className="flex flex-col items-center px-6">
                <span className="text-4xl font-bold text-green-600">+{data.improvement}%</span>
                <span className="text-sm text-gray-600 mt-1">Improvement</span>
              </div>
            </div>
            <div className="bg-gradient-to-r from-green-50 to-emerald-50 border border-green-200 rounded-xl p-6 text-center mt-6">
              <div className="text-4xl mb-3">🏆</div>
              <h2 className="text-2xl font-bold text-green-800 mb-2">
                Optimization Complete!
              </h2>
              <p className="text-lg text-green-700 mb-3">
                We fixed <span className="font-bold text-green-900">{data.total_changes || data.changes?.length || data.total_issues} issues</span> in your CV
              </p>
              <p className="text-sm text-green-600">
                ✨ What would take hours to fix manually, done in one click!
              </p>
            </div>

            {data.issues && data.issues.length > 0 && (
              <div className="mt-8 pt-6 border-t border-gray-200">
                <h3 className="text-lg font-semibold text-gray-800 mb-4 text-center">What Improved</h3>
                <div className="flex flex-wrap justify-center gap-4">
                  {(() => {
                    const severityCounts = {
                      critical: data.issues.filter(i => i.severity === 'critical').length,
                      high: data.issues.filter(i => i.severity === 'high').length,
                      medium: data.issues.filter(i => i.severity === 'medium').length,
                      low: data.issues.filter(i => i.severity === 'low').length
                    }
                    const severityConfig = [
                      { key: 'critical', label: 'Critical', icon: '🔴', bg: 'bg-red-50', text: 'text-red-700' },
                      { key: 'high', label: 'Important', icon: '🟠', bg: 'bg-orange-50', text: 'text-orange-700' },
                      { key: 'medium', label: 'Consider', icon: '🟡', bg: 'bg-yellow-50', text: 'text-yellow-700' },
                      { key: 'low', label: 'Polish', icon: '🟢', bg: 'bg-green-50', text: 'text-green-700' }
                    ]
                    return severityConfig
                      .filter(s => severityCounts[s.key as keyof typeof severityCounts] > 0)
                      .map(s => (
                        <div 
                          key={s.key} 
                          className={`flex items-center gap-2 px-3 py-2 ${s.bg} rounded-lg`}
                        >
                          <span>{s.icon}</span>
                          <span className={s.text}>{s.label}:</span>
                          <span className={`font-semibold ${s.text}`}>
                            {severityCounts[s.key as keyof typeof severityCounts]} fixed
                          </span>
                        </div>
                      ))
                  })()}
                </div>
                <p className="text-center text-sm text-gray-500 mt-3">
                  Total: {data.issues.length} issues fixed automatically
                </p>
              </div>
            )}

            {data.issues && data.issues.filter(i => i.is_auto_fixable === false).length > 0 && (
              <div className="bg-amber-50 border border-amber-200 rounded-xl p-6 mt-6">
                <div className="flex items-center gap-2 mb-4">
                  <span className="text-2xl">✏️</span>
                  <h3 className="text-xl font-bold text-gray-800">
                    {data.issues.filter(i => i.is_auto_fixable === false).length} Items Need Your Input
                  </h3>
                </div>
                
                <p className="text-gray-600 mb-4">
                  We've marked these with <span className="text-blue-600 font-semibold">[PLACEHOLDER]</span> in your CV. 
                  Replace them with your actual information:
                </p>
                
                <ul className="space-y-2 mb-4">
                  {data.issues
                    .filter(i => i.is_auto_fixable === false)
                    .map((issue) => (
                      <li key={issue.id} className="flex items-start gap-2 text-gray-700">
                        <span className="text-amber-500">•</span>
                        <span>
                          <strong>{issue.issue}</strong>
                          {issue.location && <span className="text-gray-500"> ({issue.location})</span>}
                        </span>
                      </li>
                    ))}
                </ul>
                
                <div className="bg-white rounded-lg p-3 border border-amber-100">
                  <p className="text-sm text-gray-600">
                    💡 <strong>Tip:</strong> Search for <code className="bg-gray-100 px-1 rounded">[</code> in your downloaded CV to find all placeholders quickly!
                  </p>
                </div>
              </div>
            )}
          </div>
        )}

        <div className="bg-gray-100 rounded-lg p-1 inline-flex mb-6">
          {VIEW_MODES.map(mode => {
            const Icon = mode.icon
            return (
              <button
                key={mode.id}
                onClick={() => setViewMode(mode.id)}
                className={`flex items-center gap-2 px-4 py-2 rounded-md transition-colors ${
                  viewMode === mode.id
                    ? 'bg-white shadow text-blue-600'
                    : 'text-gray-600 hover:text-gray-800'
                }`}
              >
                <Icon size={18} />
                {mode.label}
              </button>
            )
          })}
        </div>

        <div className="mb-8">
          {viewMode === 'sidebyside' && (
            <SideBySide
              left={{
                title: 'Original CV',
                content: data.original_cv_content,
                type: 'original',
                stats: {
                  label: 'Original',
                  value: '',
                  color: 'neutral',
                },
              }}
              right={{
                title: 'AI-Optimized CV',
                content: data.fixed_cv_content,
                type: 'fixed',
                changes: data.changes?.map((change) => ({
                  originalText: change.before,
                  newText: change.after,
                  category: change.category,
                  explanation: change.explanation,
                })),
                stats: {
                  label: 'changes applied',
                  value: data.changes?.length || 0,
                  color: 'green',
                },
              }}
              syncScroll={true}
              maxHeight="600px"
            />
          )}

          {viewMode === 'original' && (
            <CVPanel
              title="Original CV"
              content={data.original_cv_content}
              type="original"
              fullWidth
            />
          )}

          {viewMode === 'fixed' && (
            <CVPanel
              title="Fixed CV"
              content={data.fixed_cv_content}
              type="fixed"
              fullWidth
              changes={data.changes}
            />
          )}
        </div>

        <div className="bg-gray-50 border border-gray-200 rounded-xl p-8 text-center">
          <h2 className="text-xl font-semibold mb-2" style={{ color: '#1E3A5F' }}>
            Download Fixed CV
          </h2>
          <p className="text-gray-600 mb-6">
            Choose your preferred format
          </p>

          <div className="flex justify-center gap-4">
            <DownloadButton
              label="PDF"
              icon={FileText}
              onClick={handleDownloadPDF}
              disabled={isDownloading}
            />
            <DownloadButton
              label="DOCX"
              icon={File}
              onClick={handleDownloadWord}
              disabled={isDownloading}
            />
            <DownloadButton
              label="MD"
              icon={FileCode}
              onClick={handleDownloadMD}
              disabled={isDownloading}
            />
          </div>
        </div>

        <div className="flex justify-center gap-4 mt-8">
          <Link
            to="/dashboard"
            className="flex items-center gap-2 px-6 py-3 bg-blue-600 text-white rounded-lg hover:bg-blue-700"
          >
            <Home size={20} />
            Back to Dashboard
          </Link>
        </div>
      </div>
    </div>
  )
}

const HIGHLIGHT_STYLES: Record<string, string> = {
  quantification: 'background-color: #bbf7d0; border-bottom: 2px solid #22c55e; padding: 2px 4px; border-radius: 2px;',
  language: 'background-color: #bfdbfe; border-bottom: 2px solid #3b82f6; padding: 2px 4px; border-radius: 2px;',
  grammar: 'background-color: #fef08a; border-bottom: 2px solid #eab308; padding: 2px 4px; border-radius: 2px;',
  formatting: 'background-color: #e9d5ff; border-bottom: 2px solid #a855f7; padding: 2px 4px; border-radius: 2px;',
  default: 'background-color: #fef08a; border-bottom: 2px solid #eab308; padding: 2px 4px; border-radius: 2px;'
}

function highlightChangesInContent(content: string, changes?: Array<{ category: string; before: string; after: string; explanation: string }>): string {
  if (!changes || changes.length === 0) return content
  
  let highlightedContent = content
  
  changes.forEach(change => {
    if (change.after && change.after.length > 3) {
      const style = HIGHLIGHT_STYLES[change.category?.toLowerCase()] || HIGHLIGHT_STYLES.default
      const escapedAfter = change.after.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')
      const regex = new RegExp(escapedAfter, 'g')
      highlightedContent = highlightedContent.replace(
        regex,
        `<mark style="${style}">${change.after}</mark>`
      )
    }
  })
  
  highlightedContent = highlightedContent.replace(
    /\[([^\]]{2,50})\]/g,
    '<span style="background-color: #dbeafe; color: #1e40af; padding: 2px 4px; border-radius: 2px; border: 1px dashed #60a5fa; font-weight: 500;">[$1]</span>'
  )
  
  return highlightedContent
}

function CVPanel({ 
  title, 
  content, 
  type, 
  fullWidth = false,
  changes
}: { 
  title: string
  content: string
  type: 'original' | 'fixed'
  fullWidth?: boolean
  changes?: Array<{ category: string; before: string; after: string; explanation: string }>
}) {
  const highlightedContent = type === 'fixed' && changes ? highlightChangesInContent(content, changes) : content
  const hasHighlights = type === 'fixed' && changes && changes.length > 0

  return (
    <div className={`${fullWidth ? 'max-w-3xl mx-auto' : ''}`}>
      <div className={`flex items-center gap-2 px-4 py-3 rounded-t-lg ${
        type === 'original'
          ? 'bg-red-100 border border-red-200'
          : 'bg-green-100 border border-green-200'
      }`}>
        <div className={`w-3 h-3 rounded-full ${
          type === 'original' ? 'bg-red-500' : 'bg-green-500'
        }`}></div>
        <span className={`font-medium ${
          type === 'original' ? 'text-red-700' : 'text-green-700'
        }`}>
          {title}
        </span>
        {type === 'fixed' && changes && changes.length > 0 && (
          <span className="ml-auto text-xs bg-green-200 text-green-800 px-2 py-0.5 rounded-full">
            {changes.length} changes made
          </span>
        )}
      </div>

      <div className={`p-6 rounded-b-lg border-x border-b min-h-[500px] overflow-auto ${
        type === 'original'
          ? 'bg-red-50/30 border-red-200'
          : 'bg-green-50/30 border-green-200'
      }`}>
        {hasHighlights ? (
          <div 
            className="prose prose-sm max-w-none text-gray-800 leading-relaxed whitespace-pre-wrap"
            dangerouslySetInnerHTML={{ __html: highlightedContent }}
          />
        ) : (
          <div className="prose prose-sm max-w-none text-gray-800 leading-relaxed">
            <ReactMarkdown remarkPlugins={[remarkGfm]}>
              {content}
            </ReactMarkdown>
          </div>
        )}
        
        {type === 'fixed' && changes && changes.length > 0 && (
          <div className="mt-6 pt-4 border-t border-green-200">
            <div className="flex flex-wrap items-center gap-4 mb-3">
              <p className="text-xs font-medium text-green-700">Changes Made:</p>
              <div className="flex flex-wrap gap-3 text-xs">
                <span className="flex items-center gap-1">
                  <span className="w-4 h-4 rounded" style={{ backgroundColor: '#fef08a', borderBottom: '2px solid #eab308' }}></span>
                  Grammar
                </span>
                <span className="flex items-center gap-1">
                  <span className="w-4 h-4 rounded" style={{ backgroundColor: '#bbf7d0', borderBottom: '2px solid #22c55e' }}></span>
                  Quantification
                </span>
                <span className="flex items-center gap-1">
                  <span className="w-4 h-4 rounded" style={{ backgroundColor: '#bfdbfe', borderBottom: '2px solid #3b82f6' }}></span>
                  Language
                </span>
                <span className="flex items-center gap-1">
                  <span className="w-4 h-4 rounded" style={{ backgroundColor: '#dbeafe', border: '1px dashed #60a5fa' }}></span>
                  Needs Input
                </span>
              </div>
            </div>
            <div className="space-y-2 max-h-48 overflow-y-auto">
              {changes.slice(0, 8).map((change, idx) => (
                <div key={idx} className="text-xs bg-green-50 border border-green-200 rounded p-2">
                  <div className="flex items-center gap-1 mb-1">
                    <span className="text-green-600">✓</span>
                    <span className="font-medium text-gray-700 capitalize">{change.category}</span>
                  </div>
                  <div className="text-gray-500 line-through text-xs truncate">{change.before}</div>
                  <div className="text-green-700 text-xs truncate">→ {change.after}</div>
                </div>
              ))}
              {changes.length > 8 && (
                <p className="text-xs text-gray-500 text-center">+{changes.length - 8} more changes</p>
              )}
            </div>
          </div>
        )}
      </div>
    </div>
  )
}

function DownloadButton({ 
  label, 
  icon: Icon, 
  onClick, 
  disabled 
}: { 
  label: string
  icon: React.ElementType
  onClick: () => void
  disabled: boolean
}) {
  return (
    <button
      onClick={onClick}
      disabled={disabled}
      className="flex flex-col items-center gap-2 px-8 py-4 bg-white border border-gray-200 rounded-lg hover:bg-gray-50 hover:border-gray-300 transition-colors disabled:opacity-50"
    >
      <Icon size={32} className="text-gray-600" />
      <span className="font-medium text-gray-700">{label}</span>
    </button>
  )
}
